language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
script:
  - git version
  # git branch
  - git rev-parse --abbrev-ref HEAD
  - npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
